# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4c6880b9edab7cf3468b4a2974e9dddda2805061d84ee3ce7214e6741bbdf453b16085c577f01ace12cc5fc80d3a9623d0a22066d4849effe60aa9eebf0f7491

test:
  secret_key_base: d7f033a32d5a2b380df1bde5b09fd73d6ec1e48619eda41b9cb8ae6ede37b7191a624fbecea03c79ab9caec6f8a8e2d4cfde572b7840aae28dbb254abcf624f5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
